### ISSUE TITLE
Naive question

### ISSUE THREAD

**Issue by fmarletaz** [RemiAllio/MitoFinder#5]
Hi - thanks for this useful program. I am using it for existing assembies, and I would like to know whether it outputs somewhere the name of the Contig that was found to be the mitochondrial genomes (I could always do a blast back). That would be useful for some application. Cheers!

**Comment by RemiAllio** [comment]
Hi! 
Thank you for your feedback and relevant comment! 

Unfortunately, the name of the contig is changed during the procedure to facilitate the processing of the file. At the moment there is no output with the information but you can find it in the tmp directory if you have only one contig found as "mitochondrial-like contig". It is in the file : [SeqID]_blast_out.txt, which is the file resulting from the "blast" step of the annotation process. 

Sorry about that...

I realize now that this information can be important. In that sense, and following your comment, in the next release (coming soon, maybe at the end of the week), the information will be in a separate file.

Cheers,
Rémi

**Comment by RemiAllio** [comment]
Hi,

I just released the new version of MitoFinder (v1.3).

Thanks to your comment, a new option is born : ```--rename-contig```.
This option tells MitoFinder to rename (or not) the contig(s) matching the reference.

By default, if an existing assembly is used (-a option), this option is turned out, while it is turned on for *de novo* assembly(-1, -2 or -s options). In both cases, you can choose to enable or disable it. Finally, whether the option is used or not, the original name of the contig is specified in the file [SeqID]\_mtDNA_contig\_*.infos

Thank you again for your feedback!
Cheers,
Rémi
