### ISSUE TITLE
python while running

### ISSUE THREAD

**Issue by stachyris** [RemiAllio/MitoFinder#52]
Hi. 
I am trying to run the MitoFinder but I am encountereing following error : ``-bash: /home/vkl1/softs/MitoFinder/mitofinder: /usr/bin/python: bad interpreter: No such file or directory`` 

I am not sure where the issue is coming from - python3 is installed in /usr/bin/ but python in my $PATH is ~/miniconda/bin/python. 

Could you help me with this? 
thank you. 

Best, 
Vinay

**Comment by RemiAllio** [comment]
Hi!

MitoFinder is coded in python2.7. 
If you have python2.7 installed, you can run MitoFinder as follows:

```python2.7 /home/vkl1/softs/MitoFinder/mitofinder ```

Otherwise, I would recommend to use [MitoFinder singularity container](https://github.com/RemiAllio/MitoFinder#run-mitofinder-with-singularity).


Let me know if it helps!
Best,
Rémi

**Comment by djawdjjalodkpsaodkpw** [comment]
Hi!

MitoFinder is coded in python2.7.
If you have python2.7 installed, you can run MitoFinder as follows:

python2.7 /home/vkl1/softs/MitoFinder/mitofinder 

Otherwise, I would recommend to use [MitoFinder singularity container](https://github.com/RemiAllio/MitoFinder#run-mitofinder-with-singularity).

**Comment by stachyris** [comment]
Thanks @RemiAllio ! I used the container with singularity. It worked. Thanks! 

Also, there seems to be some kind of "spam" account commenting? FYI. 

Best, 
Vinay
