### ISSUE TITLE
tRNAs and rRNAs not printed in final reports

### ISSUE THREAD

**Issue by sihellem** [RemiAllio/MitoFinder#7]
Dear Remi,

We just tried Mitofinder but encountered some problem. Everything seems to perform correctly, and tRNAs annotation with Arwen ran well, as you can see below:
```
Starting Assembly step with MetaSPAdes 
Result files will be saved here: 
/work/BourguignonU/Menglin/Phylogeny/Neotropical_termite/NovoGen/Mitofinder/1197/1197_metaspades/
Formatting database for mitochondrial contigs identification...
Running mitochondrial contigs identification step...

MitoFinder found a single mitochondrial contig
Checking resulting contig for circularization...

Evidences of circularization could not be found, but everyother step was successful
Creating summary statistics for the mtDNA contig

Annotating

tRNA annotation with Arwen run well.

Annotation completed
Creating GFF and fasta files.

Note: 
15 genes were found in mtDNA_contig
```

However, the sequences are not printed out in the final report (see gb file attachment).

Any idea of what is going wrong?

Thanks in advance for looking into it,
Simon

[1197_mtDNA_contig.gb.txt](https://github.com/RemiAllio/MitoFinder/files/4777577/1197_mtDNA_contig.gb.txt)

**Comment by RemiAllio** [comment]
Dear Simon,

Indeed, everything seems to perform correctly. 
In the file you shared with me, the tRNAs and rRNAs are indicated.
So what do you mean by "the sequences are not printed out in the final report" ?

If you mean in the "final_genes" files, that's normal because these files render only the genes and not the tRNAs. However, the rRNAs should be included in the file "final_genes_NT".

Finally, if you want to extract the tRNAs, you should extract them using the .gff resulting from the annotation with a tool such as [bedtools](https://bedtools.readthedocs.io/en/latest/content/tools/getfasta.html)

example:
```bedtools getfasta -fi 1197_mtDNA_contig.fasta -bed 1197_mtDNA_contig.gff -fo 1197_mtDNA_contig_elements.fasta```

Does that help you?
Cheers,
Rémi

**Comment by sihellem** [comment]
Dear Rémi,

Thank you a lot for your prompt reply. My bad! As you mentioned, I could now find rRNAs in the "final_genes_NT".

Thanks a lot also for tip on extracting the tRNAs, it's very helpful.

All the best,
Cheers,
Simon

**Comment by RemiAllio** [comment]
Dear Simon,

I'm really glad my answer could help you.

Cheers,
Rémi
